### ISSUE TITLE
Decompiler

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [Lisowolf/BounceTalesReversed#1]
Hello! May you please tell which decompiler did you use? I have interest in decompiling other games =)

**Comment by Wafer-EX** [comment]
Hello, I used many decompilers, it's JD-GUI (http://java-decompiler.github.io/), JADX (https://github.com/skylot/jadx), Enigma (https://github.com/FabricMC/Enigma) that include CFR decompiler (https://github.com/leibnitz27/cfr) and Procyon decompiler (https://github.com/mstrobel/procyon) and a decompiler included to IntelliJ IDEA. No one decompiler can decompile game correctly, so it's needed to combinate result of many decompilers... Even if it seems working correctly, anyway the code can be have an issues (the Bounce Tales physics was broken in the early stages)

**Comment by Nikita-Sherstnev** [comment]
Thanks for info! Are you planning to decompile some other games?

**Comment by Wafer-EX** [comment]
No I'm not planning, it was just an experiment, a challenge for me xd

**Comment by Nikita-Sherstnev** [comment]
I see =) By any chance do you know where can I find original code of javax.microedition? I tried to use your code in my decompiled project and some classes are missing.

**Comment by Wafer-EX** [comment]
An original code is not exists, at least in free access, so it's needed to write this classes by yourself. Early I made a J2ME emulator so I know how the classes should works so it was easier for me then it could
